version: '3.4'

services:
  researchpapersrecommendationsystemandsubjectareapredictionusingdeeplearningandllmsmain:
    image: researchpapersrecommendationsystemandsubjectareapredictionusingdeeplearningandllmsmain
    build:
      context: .
      dockerfile: ./Dockerfile
